FROM scratch
MAINTAINER Bryan-Kirk Reinhardt <composer22@users.noreply.github.com>

# Copy the compiled module from the builder to this container
ADD clidemo /clidemo

CMD []
# It is important to set this -H flag with 0.0.0.0 instead of localhost to expose the server.
ENTRYPOINT ["/clidemo", "-N", "NoName", "-H", "0.0.0.0", "-p", "8080", "-L", "6060", "-W", "100"]

EXPOSE 8080 6060
