FROM scratch

MAINTAINER Bryan-Kirk Reinhardt <composer22@users.noreply.github.com>

ADD clidemo /clidemo

CMD []
ENTRYPOINT ["/clidemo", "-N", "SanFrancisco", "-p", "8081", "-L", "6061", "-W", "100"]

EXPOSE 8081 6061
